# Default values for webappv1.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace:
  name: whatthehack-webapps

service:
  name: webapp-loadbalancer
  type: LoadBalancer

deployment:
  name: nginx-webapp
  replicas: 1
  image: whatthehackmsft/nginxserver:v
  imageVersion: 1

ports:
    port: 80
    protocol: TCP
    targetPort: ui