apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    k8s-app: {{ .Values.service.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.ports.port }}
    protocol: {{ .Values.ports.protocol }}
    targetPort: {{ .Values.ports.port }}
  selector:
    k8s-app: {{ .Values.deployment.name }}